// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RameneToi.Data;

#nullable disable

namespace RameneToi.Migrations
{
    [DbContext(typeof(RameneToiWebAPIContext))]
    partial class RameneToiWebAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComposantConfigurationPc", b =>
                {
                    b.Property<int>("ComposantsId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigurationsId")
                        .HasColumnType("int");

                    b.HasKey("ComposantsId", "ConfigurationsId");

                    b.HasIndex("ConfigurationsId");

                    b.ToTable("est_composé_de", (string)null);
                });

            modelBuilder.Entity("RameneToi.Models.Adresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("RameneToi.Models.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationPcId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixConfiguration")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationPcId")
                        .IsUnique();

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("RameneToi.Models.Composant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prix")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Composants");
                });

            modelBuilder.Entity("RameneToi.Models.ConfigurationPc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomConfiguration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ConfigurationPcs");
                });

            modelBuilder.Entity("RameneToi.Models.Utilisateurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdresseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("ComposantConfigurationPc", b =>
                {
                    b.HasOne("RameneToi.Models.Composant", null)
                        .WithMany()
                        .HasForeignKey("ComposantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RameneToi.Models.ConfigurationPc", null)
                        .WithMany()
                        .HasForeignKey("ConfigurationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RameneToi.Models.Commande", b =>
                {
                    b.HasOne("RameneToi.Models.ConfigurationPc", "ConfigurationPc")
                        .WithOne("Commande")
                        .HasForeignKey("RameneToi.Models.Commande", "ConfigurationPcId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RameneToi.Models.Utilisateurs", "Utilisateur")
                        .WithMany("Commandes")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfigurationPc");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RameneToi.Models.ConfigurationPc", b =>
                {
                    b.HasOne("RameneToi.Models.Utilisateurs", "Utilisateur")
                        .WithMany("Configurations")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RameneToi.Models.Utilisateurs", b =>
                {
                    b.HasOne("RameneToi.Models.Adresse", "Adresse")
                        .WithMany("Utilisateur")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Adresses_Utilisateurs");

                    b.Navigation("Adresse");
                });

            modelBuilder.Entity("RameneToi.Models.Adresse", b =>
                {
                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RameneToi.Models.ConfigurationPc", b =>
                {
                    b.Navigation("Commande");
                });

            modelBuilder.Entity("RameneToi.Models.Utilisateurs", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
